//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CODI.rc
//
#define IDS_PARTIR                      1
#define IDS_REUNIR                      2
#define IDS_ENCRIPTAR                   3
#define IDS_DESENCRIPTAR                4
#define IDS_CONTENIDO                   5
#define IDS_ACERCADE                    6
#define IDS_SALIR                       7
#define IDSM_PARTIR                     8
#define IDSM_REUNIR                     9
#define IDSM_ENCRIPTAR                  10
#define IDSM_DESENCRIPTAR               11
#define IDSM_CONTENIDO                  12
#define IDSM_ACERCADE                   13
#define IDSM_SALIR                      14
#define IDSM_COMPARAR                   15
#define IDS_MENUCOMPARAR                16
#define IDS_MENUCONTENIDO               17
#define IDSM_PASSWORD                   18
#define IDS_PREGUNTA2                   19
#define IDS_PREGUNTA3                   20
#define IDS_PREGUNTA1                   22
#define IDSM_A_ZC                       23
#define IDS_A_ZC                        24
#define IDSM_A_QUIENESSON               25
#define IDS_MENUEXPLORAR                26
#define IDS_MENUCOMPLEMENTOS            27
#define IDS_MENUBORRAR                  28
#define IDSM_EXPLORAR                   29
#define IDSM_BORRAR                     30
#define IDSM_COMPLEMENTOS               31
#define IDSM_EXTRAER                    32
#define IDSM_OPCIONES_EXPLORACION       33
#define IDSM_CRIPTOCODI_1_0             34
#define IDS_MENUCRIPTO                  35
#define IDS_MENUDESENCRIPTAR            36
#define IDD_DLG_ABOUT                   101
#define IDI_CODI_ICON                   102
#define IDR_CODI_MENU                   103
#define IDR_ACCELERATOR                 104
#define IDB_BACKGRND                    105
#define IDB_TOOLBAR                     106
#define IDD_BUSCAR_ARCHIVO              107
#define IDB_MENU_CONTENIDO              108
#define IDD_NUMERO_ARCHIVOS             109
#define IDB_MENUACERCADE                110
#define IDB_CARPETA_CERRADA             111
#define IDB_ARCHIVO_CORTADO             112
#define IDB_ARCHIVO_FUENTE              113
#define IDD_FINALIZAR                   118
#define IDB_WIZ_BUSCAR_ARCHIVO          125
#define IDB_WIZ_NUMERO                  126
#define IDB_WIZ_FINALIZAR               127
#define IDD_DIALOG1                     128
#define IDD_BUSCAR_CARPETA              130
#define IDD_CRIPTO                      132
#define IDB_CRIPTO                      135
#define IDB_TAREA                       136
#define IDB_LOGO                        137
#define IDB_CODI                        138
#define IDB_HOT1                        141
#define IDB_HOT2                        142
#define IDB_HOT3                        143
#define IDB_HOT4                        144
#define IDB_HOT5                        145
#define IDB_HOT6                        146
#define IDB_HOT7                        147
#define IDB_TOOL1                       148
#define IDB_TOOL2                       149
#define IDB_TOOL3                       150
#define IDB_TOOL4                       151
#define IDB_TOOL5                       152
#define IDB_TOOL6                       153
#define IDB_TOOL7                       154
#define IDB_MENUCOMPARAR                155
#define IDB_MENUHELP                    156
#define IDB_MENUSALIR                   157
#define IDB_ZND                         158
#define IDD_PASSWORD                    159
#define IDD_DRAGFILES                   161
#define IDB_MENU_A_ZC                   163
#define IDB_MENUBORRAR                  165
#define IDB_MENUCOMPLEMENTOS            166
#define IDB_MENUEXPLORAR                167
#define IDB_MENUCRIPTO                  168
#define IDB_MENUDESENCRIPTAR            169
#define IDLB_1                          997
#define IDLB_PARTIR1                    998
#define IDLB_PARTIR2                    999
#define IDBT_ELEGIR_ARCHIVO             1000
#define IDRB_POR_NUMERO                 1001
#define IDBT_ELEGIR_CARPETA             1002
#define IDRB_POR_TAMANYO                1003
#define IDBT_CRIPTO_DESTINO             1004
#define IDTXT_TAMANYO                   1005
#define IDTXT_NUMERO                    1006
#define IDFRA_NUMERO                    1008
#define IDLB_NUMERO                     1009
#define IDFRA_TAMANYO                   1010
#define IDLB_TAMANYO                    1011
#define IDL_RESUMEN                     1012
#define IDBT_ELEGIR_CARPETAARCHIVO      1015
#define IDTXT_CODIGO                    1018
#define IDLB_RESUMEN                    1019
#define IDTXT_CONFIRMACION              1019
#define IDCHK_MASCARA                   1020
#define IDBT_CRIPTO_FUENTE              1021
#define IDBT_FUENTE                     1022
#define IDBT_REUNIR_DESTINO             1023
#define IDCHK_AUTOMATICO                1024
#define IDBT_SALIR                      1025
#define IDBT_DESTINO                    1026
#define IDFRA_CRIPTO                    1027
#define IDFRA_CODIGO                    1028
#define IDC_IMAGEN                      1029
#define IDLB_PREGUNTA                   1030
#define IDTX_RESPUESTA                  1031
#define IDPB_AZUL                       1032
#define IDPB_ROJO                       1033
#define IDPB_VERDE                      1034
#define IDTX_DIA                        1035
#define IDCB_MES                        1036
#define IDTX_ANYO                       1037
#define IDTX_DRAGFILE                   1040
#define IDRB_PARTIR                     1041
#define IDRB_REUNIR                     1042
#define IDRB_ENCRIPTAR                  1043
#define IDRB_DESENCRIPTAR               1044
#define IDLB_2                          1046
#define IDLB_REUNIR                     1047
#define IDM_ACERCADE                    40001
#define IDM_CONTENIDO                   40002
#define IDM_ENCRIPTAR                   40003
#define IDM_DESENCRIPTAR                40004
#define IDM_PARTIR                      40005
#define IDM_REUNIR                      40006
#define IDM_SALIR                       40007
#define IDM_COMPARAR                    40008
#define IDM_PASSWORD                    40011
#define IDM_OPCIONES_EXPLORACION        40012
#define IDM_BORRAR                      40013
#define IDM_EXTRAER                     40014
#define IDM_CRIPTOCODI_1_0              40015
#define IDM_COMPLEMENTOS                40016
#define IDM_EXPLORAR                    40017

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        173
#define _APS_NEXT_COMMAND_VALUE         40019
#define _APS_NEXT_CONTROL_VALUE         1048
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
